### PR TITLE
Add Guestfs-1.0

### PR DESCRIPTION
**Pull request by bersace**
cf. #186 
Depends on https://github.com/nemequ/vala-girs/pull/13

### CODE REVIEW

**Comment by astavale** [comment]
Hmm, not sure what the name of the VAPI should be. I've also found `libguestfs-gobject-1.0.pc`. Which name works with your Vala application?

**Comment by bersace** [comment]
@astavale You're right, actually, Guestfs-1.0.gir exposes libguestfs-gobject.

I'm using Guestfs from PyGObject.

**Comment by astavale** [comment]
Looks good. Can you just make it explicit in the description this is the GObject binding? Something like 'GObject binding to libguestfs. libguestfs provides tools for accessing and modifying virtual machine disk images.'

**Comment by bersace** [comment]
Thanks for your review @astavale .

**Comment by benwaffle** [comment]
@astavale there's no need to rebase and force push, you can squash the commits on github when merging

**Comment by astavale** [comment]
@benwaffle You mean merging in to master or merging somewhere else? For me it was just cleaner and easier to review one commit, rather that the three there would have been.

I have noticed the change of VAPI name from guestfs-1.0 to libguestfs-gobject-1.0 didn't move the entry so packages.xml is no longer alphabetical. Is that a problem?

**Comment by benwaffle** [comment]
I mean when you click the green button on github.

Alphabetical doesn't matter

**Pull request merged**
