### PR TITLE
extra-vapis: added libcolumbus

### PR DESCRIPTION
**Pull request by grindhold**
added libcolumbus to packages.xml

### CODE REVIEW

**Comment by benwaffle** [comment]
You have a typo, you wrote `libcoloumbus`

When I try to generate the valadoc, I get
```
libcolumbus.vapi:135.75-135.76: error: unexpected token: <end-of-line>
         * details at: https://bugs.launchpad.net/libcolumbus/+bug/1622424
                                                                          ^                                                             
```

**Comment by grindhold** [comment]
the travis build fails while installing dependencies :/
```
$ sudo apt-get install -y -qq valac valadoc libvaladoc-dev unzip

WARNING: The following packages cannot be authenticated!

  libgee-0.8-2 libvala-0.34-0 libvaladoc-data libvaladoc3 valadoc

  gir1.2-gee-0.8 libgee-0.8-dev valac-0.34-vapi valac libvaladoc-dev

E: There are problems and -y was used without --force-yes

The command "sudo apt-get install -y -qq valac valadoc libvaladoc-dev unzip" failed and exited with 100 during .

Your build has been stopped.
```

**Comment by benwaffle** [comment]
This looks like a PPA error. @danrabbit can you help?

**Comment by benwaffle** [comment]
It seems to be working for now. Still, the valadoc for libcolumbus seems to have a syntax error as stated above

**Comment by grindhold** [comment]
i made a PR to fix this issue https://github.com/nemequ/vala-extra-vapis/pull/42 when this pull is merged, it should probably work.

**Pull request merged**
