### PR TITLE
Fix child positioning

### PR DESCRIPTION
**Pull request by ZanderBrown**
Children where being positioned relative to the top left corner of the toplevel widget.

On Windows the window shadow is draw by Gtk causing the child widgets to overlap the edge of the window.

This change also allows the widget to be nested.

### CODE REVIEW

**Comment by ZanderBrown** [comment]
What do people think?

**Comment by benwaffle** [comment]
Not sure if it's valid code, running the code with and without the patch produces the same result

**Comment by ZanderBrown** [comment]
The existing code assumes that `allocation.x` & `allocation.y` will always be zero, however on some environments / themes (especially those using CSD) this isn't always true.

A picture is worth a thousand words:
image

**Comment by ZanderBrown** [comment]
@benwaffle ? @flobrosch ?

**Pull request merged**
