### PR TITLE
travis should build mini docs

### PR DESCRIPTION
**Pull request by benwaffle**

### CODE REVIEW

**Comment by lewisgoddard** [comment]
The travis logs seem to indicate a failure, but they don't appear to actually fail:

`ERROR: Can't generate documentation for gio-2.0. See LOG for details.`

Should this be listed as a warning instead, or should that cause a build failure?

**Comment by btkostner** [comment]
Originally those were an error that would stop the build, but I changed it in PR #27. Otherwise changes in outside code, that we have no control over, would break the whole build process.

**Comment by lewisgoddard** [comment]
Do we have a way of telling the difference between nothing building and just one item failing?

**Comment by btkostner** [comment]
The best idea I can think of would be to check for files in the build path.

**Comment by lewisgoddard** [comment]
I'm still a little concerned that building all the docs could error and this would pass build.

**Comment by benwaffle** [comment]
yup that is still an issue

**Comment by benwaffle** [comment]
I've fixed that issue.

I also rebased on master so we only have these 4 commits

**Comment by btkostner** [comment]
I have not tested it but the code looks good :+1:

**Pull request merged**
