### PR TITLE
Fix tooltips

### LINKED ISSUE #106: Tooltips collect at the bottom of the screen
Hover over a bunch of things and scroll down

@Bat41 - this is new since your es6 change

### PR DESCRIPTION
**Pull request by Bat41**
Fix #106 and #108. And they are displayed immediately (once they have been fetched, of course), you don't need to move a little bit your mouse to see them.

### CODE REVIEW

**Comment by benwaffle** [comment]
Why not just remove the tooltip on `mouseleave`?

**Comment by Bat41** [comment]
It looks like `mouseleave` is not triggered when the link is no longer here, else tooltips should have been hidden with `display: none`.

**Comment by benwaffle** [comment]
Are you saying tooltips only get destroyed on a full page load? New tooltips are created, but only hidden instead of deleted?

**Comment by ZanderBrown** [comment]
This is definitely the case when browsing via touch input

**Comment by btkostner** [comment]
There still seems to be an issue caused by the async loading of the tooltip content. It can become _very_ laggy when you move your mouse over a row of links.

**Comment by benwaffle** [comment]
Perhaps it would be better if we had a single tooltip `<div>`, and changed its contents on the fly?

**Comment by btkostner** [comment]
@benwaffle I think tooltips are already cached based on the element. At least there was significantly less lag when I hover over an element where the tooltip was already made.

I think single tooltip I think is a good idea, but the majority of the lag is coming from trying to load 20 tooltips at once in serial.

**Comment by astavale** [comment]
There is no caching on the HTTP server side. Using:

`curl --head https://valadoc.org/tooltip.php?fullname=glib-2.0/string`

returns:

```
HTTP/1.1 200 OK
Server: nginx/1.12.1
Date: Wed, 26 Jul 2017 10:26:00 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Strict-Transport-Security: max-age=63072000
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
```

There should be an `Expires:` or `Cache-Control:` header in there if you want browser side HTTP caching.

Using browser developer tools (e.g. CTRL-SHIFT + k in Firefox) shows the request is made only once for each tooltip on the page. This suggests the Javascript only generates each tooltip once in the DOM, but when the user goes to another tooltip on the page with exactly the same URL the HTTP request is made again.

Personally I think the tooltips should be inline in the HTML and use the ARIA `role="tooltip"` attribute:

 * [ARIA examples](http://heydonworks.com/practical_aria_examples/)
 * [Building a fully-accessible help tooltip ](https://www.sarasoueidan.com/blog/accessible-tooltips/)
 * [WAI-ARIA role=tooltip](http://pauljadam.com/demos/aria-role-tooltip.html)
 * [ARIA Tooltip Example](http://accessibility.athena-ict.com/aria/examples/tooltip.shtml)

**Comment by btkostner** [comment]
@astavale Doing inline tooltips might be hard with the current vala generator, but I agree with the http cache.

**Comment by benwaffle** [comment]
I'm annoyed at valadoc.org, and this is a good solution for the way we do tooltips now. We should definitely continue exploring the caching, accessibility, and one global tooltip ideas.

**Pull request merged**
